[package]
name = "h2"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]

[dependencies]
futures = "0.1"
tokio-io = { git = "https://github.com/alexcrichton/tokio-io" }
tokio-timer = { git = "https://github.com/tokio-rs/tokio-timer" }
bytes = { git = "https://github.com/carllerche/bytes" }

[replace]
"futures:0.1.10" = { git = "https://github.com/alexcrichton/futures-rs", branch = "close" }
